#!/bin/bash

feh --bg-scale $HOME/Documents/wallpaper
sxhkd &

bspc config border_width 1
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config focus_follows_pointer true
bspc config pointer_modifer mod1

bspc config automatic_scheme spiral


bspc monitor -d I II III IV V VI VII VIII IX
